databases:
  - name: masoudda
    databaseName: masoudda
    user: masoudda_user

services:
  - type: web
    name: bazarganidastvarz
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: masoudda
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
